# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.3.12
forge_version_range=[40,)
loader_version_range=[40,)
mapping_channel=official
mapping_version=1.18.2


## Mod Properties
mod_id=mininggoggles
mod_name=Mining Goggles
mod_license=MIT
mod_version=0.0.0
mod_group_id=io.wurmatron.mining_goggles
mod_authors=Wurmatron
mod_description=Prospecting made easy!\nMining Goggles adds a collection of goggles and items that allow for finding specific ores/blocks based on their "wavelength". While every block may have a wavelength by default only ores have them (configurable in the config). The goggles look for specific wavelengths to display, depending on your goggle's quality and tuned wavelength will determine its rendering range.
