modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/Wurmatron/Mining-Goggles/issues"
[[mods]]
modId="mininggoggles"
version="${file.jarVersion}"
displayName="Mining Goggles"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mining-goggles"
logoFile="logo.png"
credits=""
authors="Wurmatron"
description='''
Mining Goggles is a mod designed to render the OreDictionary visually.
'''
[[dependencies.mininggoggles]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mininggoggles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
